/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherNotesRouteImport } from './routes/teacher.notes'
import { Route as TeacherMessagesRouteImport } from './routes/teacher/messages'
import { Route as TeacherCalendarRouteImport } from './routes/teacher.calendar'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentMessagesRouteImport } from './routes/student/messages'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotesRoute = TeacherNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/results': typeof StudentResultsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/results': typeof StudentResultsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/results': typeof StudentResultsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/admin/messages'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/materials'
    | '/student/messages'
    | '/student/results'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/messages'
    | '/teacher/notes'
    | '/teacher/results'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/messages'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/materials'
    | '/student/messages'
    | '/student/results'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/messages'
    | '/teacher/notes'
    | '/teacher/results'
    | '/teacher/students'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/admin/messages'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/materials'
    | '/student/messages'
    | '/student/results'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/messages'
    | '/teacher/notes'
    | '/teacher/results'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notes': {
      id: '/teacher/notes'
      path: '/notes'
      fullPath: '/teacher/notes'
      preLoaderRoute: typeof TeacherNotesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMessagesRoute: typeof AdminMessagesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMessagesRoute: AdminMessagesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherNotesRoute: typeof TeacherNotesRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherNotesRoute: TeacherNotesRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
